### ISSUE TITLE
Check Docker-Container Geoserver

### ISSUE THREAD

**Issue by EPajares** [EPajares/goat#186]
**After booting the machine the container is not starting.**
**This is the log**

`goat-geoserver  | 26-Oct-2019 17:34:47.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.53
goat-geoserver  | 26-Oct-2019 17:34:47.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 29 2018 14:42:45 UTC
goat-geoserver  | 26-Oct-2019 17:34:47.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.53.0
goat-geoserver  | 26-Oct-2019 17:34:47.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
goat-geoserver  | 26-Oct-2019 17:34:47.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-66-generic
goat-geoserver  | 26-Oct-2019 17:34:47.643 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-1~deb9u1-b13
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
goat-geoserver  | 26-Oct-2019 17:34:47.644 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
goat-geoserver  | 26-Oct-2019 17:34:47.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
goat-geoserver  | 26-Oct-2019 17:34:47.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
goat-geoserver  | 26-Oct-2019 17:34:47.645 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms2G
goat-geoserver  | 26-Oct-2019 17:34:47.646 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx4G
goat-geoserver  | 26-Oct-2019 17:34:47.646 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xrs
goat-geoserver  | 26-Oct-2019 17:34:47.646 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:PerfDataSamplingInterval=500
goat-geoserver  | 26-Oct-2019 17:34:47.646 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.referencing.forceXY=true
goat-geoserver  | 26-Oct-2019 17:34:47.646 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SoftRefLRUPolicyMSPerMB=36000
goat-geoserver  | 26-Oct-2019 17:34:47.647 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParallelGC
goat-geoserver  | 26-Oct-2019 17:34:47.647 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:NewRatio=2
goat-geoserver  | 26-Oct-2019 17:34:47.647 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+CMSClassUnloadingEnabled
goat-geoserver  | 26-Oct-2019 17:34:47.647 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dfile.encoding=UTF8
goat-geoserver  | 26-Oct-2019 17:34:47.648 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=GMT
goat-geoserver  | 26-Oct-2019 17:34:47.648 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.request.encoding=UTF-8
goat-geoserver  | 26-Oct-2019 17:34:47.648 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.servlet.response.encoding=UTF-8
goat-geoserver  | 26-Oct-2019 17:34:47.648 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=GMT
goat-geoserver  | 26-Oct-2019 17:34:47.648 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.shapefile.datetime=true
goat-geoserver  | 26-Oct-2019 17:34:47.649 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.geotools.shapefile.datetime=true
goat-geoserver  | 26-Oct-2019 17:34:47.649 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Ds3.properties.location=/opt/geoserver/data_dir/s3.properties
goat-geoserver  | 26-Oct-2019 17:34:47.649 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xbootclasspath/a:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin.jar
goat-geoserver  | 26-Oct-2019 17:34:47.649 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xbootclasspath/p:/usr/local/tomcat/webapps/geoserver/WEB-INF/lib/marlin-sun-java2d.jar
goat-geoserver  | 26-Oct-2019 17:34:47.649 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dsun.java2d.renderer=org.marlin.pisces.PiscesRenderingEngine
goat-geoserver  | 26-Oct-2019 17:34:47.650 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
goat-geoserver  | 26-Oct-2019 17:34:47.650 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
goat-geoserver  | 26-Oct-2019 17:34:47.650 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
goat-geoserver  | 26-Oct-2019 17:34:47.650 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
goat-geoserver  | 26-Oct-2019 17:34:47.651 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
goat-geoserver  | 26-Oct-2019 17:34:47.651 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
goat-geoserver  | 26-Oct-2019 17:34:47.651 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.2.17 using APR version 1.5.2.
goat-geoserver  | 26-Oct-2019 17:34:47.651 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
goat-geoserver  | 26-Oct-2019 17:34:47.654 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.1.0f  25 May 2017)
goat-geoserver  | 26-Oct-2019 17:34:47.753 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
goat-geoserver  | 26-Oct-2019 17:34:47.762 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
goat-geoserver  | 26-Oct-2019 17:34:47.764 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 432 ms
goat-geoserver  | 26-Oct-2019 17:34:47.788 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
goat-geoserver  | 26-Oct-2019 17:34:47.789 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.53
goat-geoserver  | 26-Oct-2019 17:34:47.805 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/host-manager
goat-geoserver  | 26-Oct-2019 17:34:48.136 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/host-manager has finished in 330 ms
goat-geoserver  | 26-Oct-2019 17:34:48.136 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/manager
goat-geoserver  | 26-Oct-2019 17:34:48.162 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/manager has finished in 26 ms
goat-geoserver  | 26-Oct-2019 17:34:48.163 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/examples
goat-geoserver  | 26-Oct-2019 17:34:48.387 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/examples has finished in 223 ms
goat-geoserver  | 26-Oct-2019 17:34:48.387 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/docs
goat-geoserver  | 26-Oct-2019 17:34:48.407 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/docs has finished in 19 ms
goat-geoserver  | 26-Oct-2019 17:34:48.407 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/ROOT
goat-geoserver  | 26-Oct-2019 17:34:48.426 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 19 ms
goat-geoserver  | 26-Oct-2019 17:34:48.428 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/geoserver
goat-geoserver  | 26-Oct-2019 17:34:49.840 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start:
goat-geoserver  |  org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
goat-geoserver  |       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
goat-geoserver  |       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:755)
goat-geoserver  |       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
goat-geoserver  |       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
goat-geoserver  |       at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
goat-geoserver  |       at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
goat-geoserver  |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
goat-geoserver  |       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
goat-geoserver  |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
goat-geoserver  |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
goat-geoserver  |       at java.lang.Thread.run(Thread.java:748)
goat-geoserver  | Caused by: java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/geoserver] due to a StackOverflowError. Possible root causes include a too low setting for -Xss and illegal cyclic inheritance dependencies. The class hierarchy being processed was [org.sqlite.SQLiteConnection->org.sqlite.jdbc4.JDBC4Connection->org.sqlite.jdbc3.JDBC3Connection->org.sqlite.SQLiteConnection]
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.checkHandlesTypes(ContextConfig.java:2098)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.processAnnotationsStream(ContextConfig.java:2044)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.processAnnotationsJar(ContextConfig.java:1989)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.processAnnotationsUrl(ContextConfig.java:1959)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.processAnnotations(ContextConfig.java:1913)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1156)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:773)
goat-geoserver  |       at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:307)
goat-geoserver  |       at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:95)
goat-geoserver  |       at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
goat-geoserver  |       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5262)
goat-geoserver  |       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
goat-geoserver  |       ... 10 more
goat-geoserver  |
goat-geoserver  | 26-Oct-2019 17:34:49.841 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Error deploying web application directory /usr/local/tomcat/webapps/geoserver
goat-geoserver  |  java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/geoserver]]
goat-geoserver  |       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:759)
goat-geoserver  |       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:731)
goat-geoserver  |       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
goat-geoserver  |       at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
goat-geoserver  |       at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1868)
goat-geoserver  |       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
goat-geoserver  |       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
goat-geoserver  |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
goat-geoserver  |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
goat-geoserver  |       at java.lang.Thread.run(Thread.java:748)
goat-geoserver  |
goat-geoserver  | 26-Oct-2019 17:34:49.842 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/geoserver has finished in 1,415 ms
goat-geoserver  | 26-Oct-2019 17:34:49.846 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
goat-geoserver  | 26-Oct-2019 17:34:49.856 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
goat-geoserver  | 26-Oct-2019 17:34:49.860 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 2095 ms`

**Comment by EPajares** [comment]
@majkshkurti maybe you find a solution for this?

**Comment by EPajares** [comment]
We found another Geoserver image
